/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/ping_pong_paddle_scanned_with_academia_50/scene.gltf -t -r -public
Author: Creaform 3D (https://sketchfab.com/creaform)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ping-pong-paddle-scanned-with-academia-50-43565fda2deb470fbe86e5561a2e1e4e
Title: Ping pong Paddle scanned with ACADEMIA 50
*/

import * as THREE from 'three';
import React, { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';
import { useBox } from '@react-three/cannon';
import { useMainStore } from '../state/mainStore';
import pingSound from '../resources/ping.mp3';
import { clamp } from 'three/src/math/MathUtils';

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshStandardMaterial;
  };
};

export interface PaddleProps {
  args?: number[] | undefined;
  handleScoreChange: (calculationKey: string) => void;
}

export const Paddle: React.FC<PaddleProps> = ({ handleScoreChange }) => {
  const { nodes, materials } = useGLTF(
    '/scene-transformed.glb'
  ) as unknown as GLTFResult;
  const ping = new Audio(pingSound);

  const pongSound = (velocity: number) => {
    ping.volume = clamp(velocity / 50, 0.1, 1);
    ping.play();
  };

  useFrame(({ viewport, mouse }) => {
    api.position.set((mouse.x * viewport.width) / 2, mouse.y * 20, 0);
    api.rotation.set(0, 0, -Math.PI / 2 + mouse.x / 2);
  });

  const [ref, api] = useBox(() => ({
    args: [0.5, 8, 8.5],
    mass: 0,
    rotation: [0, 0, Math.PI / 2],
    onCollide: (e) => {
      handleScoreChange('+');
      pongSound(e.contact.impactVelocity);
    }
  }));

  return (
    <group dispose={null} scale={0.05} ref={ref} castShadow receiveShadow>
      <group position={[-1, 0, 180]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.material}
        />
      </group>
    </group>
  );
};

useGLTF.preload('/scene-transformed.glb');
